server:
  port: 80801
spring:
  cloud:
    config:
      server:
        git:
          default-label: fantan
          uri: https://github.com/Diegodaho/microservicio.git
          search-paths: config-data
  application:
    name: config-service
          
